### PR TITLE
Fix some terms

### PR DESCRIPTION
**Pull request by manhcuong0312**
I updated some term to make it more familiar with Vietnamese people. There are two string I translated, but it still appear as English:

- Default action in interactive mode (in `Settings
->General`)
- Port (in `settings->web server`)

Please check and fix it, or tell me if I did something cause that error.  
Thank you.

### CODE REVIEW

**Comment by AAClause** [comment]
Hello,
Please use the latest .pot file. You can download it here -> https://andreabc.net/projects/NVDA_addons/markdownForever/l10n (permanent link).
Thanks! :)

**Comment by manhcuong0312** [comment]
> Please use the latest .pot file.

Done! I don't know there were a newer file until read your comment.  
Thank you.

**Comment by manhcuong0312** [comment]
Oh a thing I forgot to ask. What should I do to know if there are updated .pot file? Thank you

**Comment by AAClause** [comment]
Unfortunately I don't have a quick solution for that. The .pot file is regenerated each time that a new version is released. The best is re-download the file from time to time (or just when you found new strings in the interface).
Keep in mind that in Poedit you can show the untranslated strings at the beginning of the list.
Thanks

**Pull request merged**
