### PR TITLE
updated Vietnamese localization

### PR DESCRIPTION
**Pull request by manhcuong0312**
- Changed latex reference link to Vietnamese wikipedia page
- minor fixes in documentation and interface file.

### CODE REVIEW

**Review by AAClause — APPROVED** [review]
Thanks @manhcuong0312!

**Comment by manhcuong0312** [comment]
Hi  
I try generating pot file for this add-on using scons pot command, and got the error I attached here. If you have time, please help me. I just install thing required for add-on development, not install any module from dependencies.md. Is this cause problem?  
Thank you.
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\python37\Scripts\scons.exe\__main__.py", line 7, in <module>
Generating pot file markdownForever.pot
xgettext: warning: ’’utf-8’’ is not a valid encoding name. Using ASCII as fallback.
xgettext: Non-ASCII string at addon\globalPlugins\markdownForever\HTTPServer.py:63.
Please specify the source encoding through --from-code or through a comment
as specified in https://www.python.org/peps/pep-0263.html.
scons: *** [markdownForever.pot] Error 1
scons: building terminated because of errors.
```

**Comment by AAClause** [comment]
- How did you install gettext?
- What is the output of the following command in cmd:
  `where xgettext`

If you have installed git, I recommend you add its bin folder path to the Windows PATH variable (in my case it's "C:\Program Files\Git\usr\bin"). Indeed gettext is included with git.
HTH

**Comment by manhcuong0312** [comment]
Hi Andre  
I installed gettext by downloading it zip file from [this link](https://mlocati.github.io/articles/gettext-iconv-windows.html), unzip to a folder I want, then add path to user environment so I don't need to copy some executable files it to add-on folder as said in the add-on development.  
I installed git, and it the installer already add the bin folder to path like you said.First, I think the error may cause by python 3.7.9, which is the latest 3.7 version, then I installed 3.7.8, and this error still occur with your add-on, but not for another one. Below are errors output I sent in my previous comment:  
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\python37\Scripts\scons.exe\__main__.py", line 7, in <module>
Generating pot file markdownForever.pot
xgettext: warning: ’’utf-8’’ is not a valid encoding name. Using ASCII as fallback.
xgettext: Non-ASCII string at addon\globalPlugins\markdownForever\HTTPServer.py:63.
Please specify the source encoding through --from-code or through a comment
as specified in https://www.python.org/peps/pep-0263.html.
scons: *** [markdownForever.pot] Error 1
scons: building terminated because of errors.
```
Thanks for your time.

**Pull request merged**
